controller_manager:
  ros__parameters:
    update_rate: 10

    rigid_pose_broadcaster:
      type: rigid_pose_broadcaster/RigidPoseBroadcaster


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


rigid_pose_broadcaster:
  ros__parameters:  
    state_publish_rate: 10
    sensor_names:
      - fus_tracker
      - needle
    sensor_ids:
      - 1998
      - 2023
    world_frame: polaris_frame


joint_state_broadcaster:
  ros__parameters:
    state_publish_rate: 10
    state_interface_names:
      - pose.position.x
      - pose.position.y
      - pose.position.z
      - pose.orientation.x
      - pose.orientation.y
      - pose.orientation.z
      - pose.orientation.w


joint_state_broadcaster:
  ros__parameters:
    state_publish_rate: 10
    state_interface_names:
      - pose.position.x
      - pose.position.y
      - pose.position.z
      - pose.orientation.x
      - pose.orientation.y
      - pose.orientation.z
      - pose.orientation.w